
---===Error===---
Time = 28.03.2017 20:49:07Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\staff.py", line 822, in acc
    parametrs = (self.de_notification.date().toString(Qt.ISODate, self.le_notofication.toPlainText()), self.id_info)
TypeError: arguments did not match any overloaded call:
  QDate.toString(Qt.DateFormat format=Qt.TextDate): too many arguments
  QDate.toString(str): argument 1 has unexpected type 'DateFormat'

---===Error===---
Time = 18.08.2017 14:26:52Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\report_cost_article.py", line 74, in ui_calc_cost
    text = re.sub(r'(?<=\d)(?=(\d\d\d)+\b.)', ' ', str(round(material[4], 2)))
TypeError: type NoneType doesn't define __round__ method

---===Error===---
Time = 18.08.2017 14:29:16Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\report_cost_article.py", line 70, in ui_calc_cost
    text = re.sub(r'(?<=\d)(?=(\d\d\d)+\b.)', ' ', str(round(material[3], 2)))
TypeError: type NoneType doesn't define __round__ method

---===Error===---
Time = 18.08.2017 16:29:26Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 2000, in ui_acc
    self.main.of_ex_ttn(addres, article)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1417, in of_ex_ttn
    sheet["B7"] = self.le_ttn_auto.text()
AttributeError: 'Order' object has no attribute 'le_ttn_auto'

---===Error===---
Time = 18.08.2017 17:03:29Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1987, in ui_acc
    self.main.of_ex_invoice(addres, article)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1378, in of_ex_invoice
    book.save(path[0])
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 342, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 264, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:/Users/Meller/Desktop/1.xlsx'

---===Error===---
Time = 18.08.2017 17:05:45Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1987, in ui_acc
    self.main.of_ex_invoice(addres, article)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1378, in of_ex_invoice
    book.save(path[0])
  File "C:\Python34\lib\site-packages\openpyxl\workbook\workbook.py", line 342, in save
    save_workbook(self, filename)
  File "C:\Python34\lib\site-packages\openpyxl\writer\excel.py", line 264, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Python34\lib\zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
PermissionError: [Errno 13] Permission denied: 'C:/Users/Meller/Desktop/1.xlsx'

---===Error===---
Time = 18.08.2017 18:47:21Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1986, in ui_acc
    self.main.of_ex_torg12(edo, head, article, addres)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\order.py", line 1093, in of_ex_torg12
    sheet["N%s" % row_ex] = moneyfmt.moneyfmt(no_nds_price)
  File "C:/Users/Meller/Desktop/CRM-Avi\function\moneyfmt.py", line 29, in moneyfmt
    sign, digits, exp = value.quantize(q).as_tuple()
AttributeError: 'float' object has no attribute 'quantize'

---===Error===---
Time = 21.08.2017 13:50:01Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\main_window.py", line 185, in view_product
    self.article_list = article.ArticleList()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\templates\tree.py", line 21, in __init__
    self.access()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\templates\tree.py", line 36, in access
    a(item["value"])
TypeError: QAction.setEnabled(bool): argument 1 has unexpected type 'str'

---===Error===---
Time = 21.08.2017 13:59:23Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 125, in ui_double_click_table_item
    self.ui_change_table_item(item.data(5))
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 105, in ui_change_table_item
    self.new_operation = Article(self, item_id)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 172, in __init__
    self.access()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 178, in access
    a = getattr(a, item["atr2"])
AttributeError: 'bool' object has no attribute 'False'

---===Error===---
Time = 21.08.2017 14:00:25Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 125, in ui_double_click_table_item
    self.ui_change_table_item(item.data(5))
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 105, in ui_change_table_item
    self.new_operation = Article(self, item_id)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 172, in __init__
    self.access()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\article.py", line 187, in access
    a(val)
TypeError: 'bool' object is not callable

---===Error===---
Time = 21.08.2017 14:39:26Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\pack.py", line 244, in ui_double_click_operation
    if not self.toolButton_8.enabled:
AttributeError: 'QToolButton' object has no attribute 'enabled'

---===Error===---
Time = 21.08.2017 14:41:03Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\pack.py", line 244, in ui_double_click_operation
    if not self.toolButton_8.enabled():
AttributeError: 'QToolButton' object has no attribute 'enabled'

---===Error===---
Time = 21.08.2017 15:21:51Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\staff.py", line 131, in double_click
    self.add_mat = OneStaff(self, True)
  File "C:/Users/Meller/Desktop/CRM-Avi\form\staff.py", line 277, in __init__
    self.access()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\staff.py", line 292, in access
    a(val)
TypeError: QWidget.show(): too many arguments

---===Error===---
Time = 22.08.2017 15:09:09Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\main_window.py", line 233, in view_audit_verification
    self.audit_verification = audit.AuditVerification()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\audit.py", line 21, in __init__
    int("dd")
ValueError: invalid literal for int() with base 10: 'dd'
